POST http://localhost:3000/memes/fa12236a-12e7-42f1-822b-237b9e848df9/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5Nzg5YTA5Yi1mMDI0LTRkM2EtYTY2OC1jZDdlYTc1MzdlZjQiLCJ1c2VyTmFtZSI6InJpY2NhcmRvMiIsImlhdCI6MTc1MDE3MDE3MywiZXhwIjoxNzUwMjU2NTczfQ.z2rFun99v0yKjVsEZkZWIvXlSCh4nIOwKNp8GQjAANA

{
  "content": "How can it be funny? It's just a picture of a cat...",
  "parentId": "430caf6f-05d4-42ce-b6f7-432fb5b8d222"
}